- name: running finalization command
  shell: "{{item}}"
  sudo: "{{deploy.finalize.required_sudo}}"
  with_items: deploy.finalize.commands

- name: restarting services
  service: name="{{item}}" state=restarted
  sudo: "{{deploy.finalize.required_sudo}}"
  with_items: deploy.finalize.to_be_restarted_services